spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.67464d62a6714940
            clientSecret: 5d16783f601f8252363b321be93cbb07df6fe5d5
          google:
            client-id: 342023897853-41vs1ilf1v78s8d5bj6v1gqb61k33irp.apps.googleusercontent.com
            client-secret: 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
            
         
            
        
        
        
        
        
        
        
        
        
        
        
       
             
         
                     
      
      
  application:
    name: MovieToWatch            
 
  datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/movietowatch1
     username: root
     password: 
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true            